[target.aarch64-linux-android]
linker = "C:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk\\ndk\\android-ndk-r27d\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android28-clang.cmd"
ar = "C:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk\\ndk\\android-ndk-r27d\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"

[env]
CC_aarch64-linux-android = "C:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk\\ndk\\android-ndk-r27d\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android28-clang.cmd"
AR_aarch64-linux-android = "C:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk\\ndk\\android-ndk-r27d\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
CFLAGS_aarch64-linux-android = "--target=aarch64-linux-android28"
